server:
  port: 7001
eureka:
  instance:
    hostname: localhost   #Eureka服务端的名称
  client:
    register-with-eureka: false #是否向eureka注册中心注册自己，这里是eureka注册中心，所以不用注册自己
    fetch-registry: false      #为false表示自己是注册中心
    service-url:   #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
#  server:
#    enable-self-preservation: false   #关闭eureka的自我保护机制

