spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: consumer
  rabbitmq:
    host: 192.168.68.149
    port: 5672
    username: admin
    password: 111111
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 10
        retry:
          enabled: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${server.port}

hystrix:
  command:
    default:
      circuitBreaker:
        forceOpen: false
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 5000
        requestVolumeThreshold: 10
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

server:
  port: 8001

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"



