spring:
  profiles:
    active: dev7001

---
server:
  port: 7001
spring:
  profiles: dev7001
  application:
    name: zccenter-dev7001
eureka:
  instance:
    hostname: localhost   #Eureka服务端的名称
  client:
    register-with-eureka: false #是否向eureka注册中心注册自己，这里是eureka注册中心，所以不用注册自己
    fetch-registry: false      #为false表示自己是注册中心
    service-url:   #监控页面
      defaultZone: http://localhost:7002/eureka,http://localhost:7003/eureka  #单个的换此次值为自己的ip和端口，集群的话值为其他服务的ip和端口，逗号分隔
#  server:
#    enable-self-preservation: false   #关闭eureka的自我保护机制

---
server:
  port: 7002
spring:
  profiles: dev7002
  application:
    name: zccenter-dev7002
eureka:
  instance:
    hostname: localhost   #Eureka服务端的名称
  client:
    register-with-eureka: false #是否向eureka注册中心注册自己，这里是eureka注册中心，所以不用注册自己
    fetch-registry: false      #为false表示自己是注册中心
    service-url:   #监控页面
    #eureka集群，必须3个起步
      defaultZone: http://localhost:7001/eureka,http://localhost:7003/eureka
