spring:
  application:
    name: zuul
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: zuul
    prefer-ip-address: true
zuul:
  routes:
    consumer:
      serviceId: consumer
      path: /consumer/**
#   ignored-services: "*"
  prefix: /hy
